// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfTj8j8HhHX4N5PJh9kW3XGQJgXgzLnG8',
    appId: '1:1056451019372:web:dc20911794dcc7923fce49',
    messagingSenderId: '1056451019372',
    projectId: 'fir-flutter-codelab-c2111',
    authDomain: 'fir-flutter-codelab-c2111.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c2111.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRigrryY5JcKdrOdJEsuN2RHC18JK5P9c',
    appId: '1:1056451019372:android:a9290ffb4f07c1f43fce49',
    messagingSenderId: '1056451019372',
    projectId: 'fir-flutter-codelab-c2111',
    storageBucket: 'fir-flutter-codelab-c2111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlA_tnxVCP5qSW6EPLqo_ATDWpj286Qec',
    appId: '1:1056451019372:ios:1f65ed881433a7453fce49',
    messagingSenderId: '1056451019372',
    projectId: 'fir-flutter-codelab-c2111',
    storageBucket: 'fir-flutter-codelab-c2111.appspot.com',
    iosClientId: '1056451019372-moard4dk84i6t2289e33quihfhdhurl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlA_tnxVCP5qSW6EPLqo_ATDWpj286Qec',
    appId: '1:1056451019372:ios:1f65ed881433a7453fce49',
    messagingSenderId: '1056451019372',
    projectId: 'fir-flutter-codelab-c2111',
    storageBucket: 'fir-flutter-codelab-c2111.appspot.com',
    iosClientId: '1056451019372-moard4dk84i6t2289e33quihfhdhurl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
